version: "3.9"

services:
  client:
    build:
      context: client
      dockerfile: dockerfile
    image: youtube-trends-client:latest
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    container_name: "youtube-trends-client"

  notebook:
    build:
      context: notebook
      dockerfile: dockerfile
    image: youtube-trends-notebook:latest
    command: jupyter notebook --config=config.json
    ports:
      - 8888:8888
    volumes:
      - ./notebook:/usr/src/app
      - ./.data:/usr/src/app/data
    environment:
      - KAGGLE_USER=sajalshres
      - KAGGLE_KEY=f6a2fb9a63d829211573b1c3201afe0d
    container_name: "youtube-trends-notebook"
