version: "3.9"

services:
  client:
    build:
      context: client
      dockerfile: dockerfile.prod
    image: youtube-trends-client:prod
    ports:
      - 9000:9000
    depends_on:
      - mongodb
    container_name: youtube-trends-client-prod

  client-dev:
    build:
      context: client
      dockerfile: dockerfile
    image: youtube-trends-client:latest
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - mongodb
    container_name: youtube-trends-client

  server:
    build:
      context: server
      dockerfile: dockerfile
    image: youtube-trends-server:latest
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./server/app:/usr/src/app
    depends_on:
      - mongodb
    environment:
      APP_NAME: Youtube Trends Analysis
      APP_VERSION: 0.0.1
      APP_MONGODB_URI: mongodb://admin:Admin#2022@mongodb:27017
      APP_DATABASE_NAME: youtube_trend_db
      APP_REDIS_URI: redis://redis:6379

    container_name: youtube-trends-server

  notebook:
    build:
      context: notebook
      dockerfile: dockerfile
    image: youtube-trends-notebook:latest
    command: jupyter notebook --config=config.json
    ports:
      - 8888:8888
    volumes:
      - ./notebook:/usr/src/app
      - ./.data:/usr/src/app/src/data
    depends_on:
      - mongodb
    environment:
      KAGGLE_USERNAME: sajalshres
      KAGGLE_KEY: f6a2fb9a63d829211573b1c3201afe0d
      MONGO_USERNAME: admin
      MONGO_PASSWORD: Admin#2022
    container_name: youtube-trends-notebook

  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin#2022
    container_name: youtube-trends-mongodb

  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
    volumes:
      - $PWD/.redis:/data
    command: --dir /data
    container_name: youtube-trends-redis
